services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: node_container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    driver: bridge
